apiVersion: apps/v1
kind: Deployment
metadata:
  name: monsuperdrive-deployment
  labels:
    app: monsuperdrive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monsuperdrive
  template:
    metadata:
      labels:
        app: monsuperdrive 
    spec:
      containers:
      - name: monsuperdrive
        image: registry.gitlab.com/jojo73/monsuperdrive/tiers2:1.0.0
        ports:
        - containerPort: 9000

# le protocole tcp se fait sur le service