# BottleNovole-Blagafac: Service
apiVersion: v1
kind: Service
metadata:
  name: monsuperdrive-service
spec:
  selector:
    app: monsuperdrive
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000